#!/usr/bin/env bash
# Install your load balancer
sudo apt update
sudo apt upgrade
sudo apt install haproxy
echo -e "\nfrontend myfrontend\n\tbind *:80\n\tmode http\n\tdefault_backend mybackend\n\nbackend mybackend\n\tbalance roundrobin\n\tserver 330491-web-01 54.161.254.60:80 check\n\tserver 330491-web-02 54.167.200.160:80 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart