#!/usr/bin/env bash
# Install your load balancer
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get -y update
apt-get -y install haproxy=2.0.\*
echo -e "\nfrontend myfrontend\n\tbind *:80\n\tmode http\n\tdefault_backend mybackend\n\nbackend mybackend\n\tbalance roundrobin\n\tserver 330491-web-01 54.161.254.60:80 check\n\tserver 330491-web-02 54.167.200.160:80 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart