#!/usr/bin/env bash
# Install your load balancer
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get -y update
apt-get -y install haproxy=2.0.\*
echo -e "\nfrontend myfrontend\n\tbind *:80\n\tmode http\n\tdefault_backend mybackend\n\nbackend mybackend\n\tbalance roundrobin\n\tserver 330491-web-01 100.26.133.152:80 check\n\tserver 330491-web-02 100.25.130.218:80 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart