#!/usr/bin/env bash
# Changing the nginx configuration file to listen on port 80
sed -i "s/8080/80/g" /etc/nginx/sites-enabled/default
sed -i "s/ ipv6only=on//" /etc/nginx/sites-available/default
service nginx restart
