#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 100
x=1
while [ "$x" -le 100 ]
do
	if [ $((x % 5)) -eq 0 ] && [ $((x % 3)) -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ $((x % 5)) -eq 0 ]
	then
		echo "Buzz"
	elif [ $((x % 3)) -eq 0 ]
	then
		echo "Fizz"
	else
		echo "$x"
	fi
	((x++))
done
