#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes
hours=0
while [ "$hours" -le 12 ]
do
	echo "Hour: $hours"
	min=1
	while [ "$min" -lt 60 ]
	do
		echo "$min"
		((min++))
	done
	((hours++))
done
